triggers:
  - type: page_open
  - keyword: start

steps:
  - value: (@ flow.context.get("demo") )
    match:
      strava:
        flow: flow.strava.start
        transfer: true
    default: next

  - say: Hey, welcome!
