triggers:
  - type: page_open
  - keyword: start

steps:
  - type: meya.user.component.try_reverse_lookup
    integration: integration.orb
  - user_set:
      user_id: (@ flow.result )
  - value: (@ flow.context.demo )
    match:
      strava:
        flow: flow.strava.start
        transfer: true
    default: next

  - say: Hey, welcome!
