triggers:
  - keyword: escalate

steps:
  - type: component.strava.auth
    user_id: (@ user.user_id )
    url: (@ vault.strava.api.url )
    api_token: (@ vault.strava.api.token )
  - if: (@ flow.result )
    then:
      user_set:
        name: (@ flow.name )
        email: (@ flow.email )
        is_paid: (@ flow.is_paid )
    else: end

  - if: (@ user.is_paid )
    then:
      flow: flow.strava.support.chat.session.start
    else:
      flow: flow.strava.support.ticket.create
